### ISSUE TITLE
decide the structure of data of users

### ISSUE THREAD

**Issue by zuewang** [o3n/teamform-seed#24]
to achieve synchronization with firebase

**Comment by coeusguo** [comment]
sofa

**Comment by coeusguo** [comment]
My Idea:

user:
{name:"Peter",username:"cspeter",password:"123456",skillTag:["java","c++",.......],teamID:"We Love Peter"(NULL ,if no team currently),notification:[{type:"request",from:"csbb",dialogID:"cspetervcsbb"}]}
user profile picture address: userProfileImage/{{username}}.jpg/png

team:
{teamID:"helloworld" teamName:"We Love Peter",teamMember:["cspeter","csbb","sung"],skillTag:["java","html",.........]}
team profile image address: teamProfileImage/{{teamID}}.jpg/png

dialog
{dialogID:"cspetervcsbb",message:[ {date:"06-09-2016",message:"do you love sung?"},{date:"07-09-2016",message:"love!sung"} ] }
